// import { Cart, Footer, FooterBanner, HeroBanner, Layout, NavBar, Product } from '../components';
import Head from 'next/head';
import { Product, FooterBanner, HeroBanner, } from '../components';

export default function Home() {
  const dummyProducts = ['Products 1 ', 'Products 2 ', 'Products 3 ', 'Product 4 '];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <HeroBanner />
          <div className="products-heading">
            <h1>Best Selling Products</h1>
            <p>Speakers of many variations</p>
          </div>
          <div>
            {dummyProducts.map((Product) => (Product))}
          </div>
        </div>
      </main>
    </>
  );
}
