// import { Cart, Footer, FooterBanner, HeroBanner, Layout, NavBar, Product } from '../components';
import Head from 'next/head';
import { Product, FooterBanner, HeroBanner, } from '@/components';
import { client } from '@/lib/client';

export default function Home({ products, bannerData }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <HeroBanner heroBanner={bannerData.length && bannerData[0]} />
          <div className="products-heading">
            <h1>Best Selling Products</h1>
            <p>Speakers of many variations</p>
          </div>
          <div>
            {products?.map((product: any) => (product.name))}
          </div>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type=="product"]';
  const products = await client.fetch(query);
  const bannerQuery = '*[_type=="banner"]';
  const bannerData = await client.fetch(bannerQuery);

  return {
    props: { products, bannerData }
  };
};